spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  jwtSecret: ${SECRET_WORD:secret}
  issuer: ${ISSUER:issuer}
  subject: ${SUBJECT:subject}
  claimName: ${CLAIM_NAME:username}

urls:
  appUrl: localhost
