name: Java CI with Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  security-scanning:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: OWASP Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'spring-boot-app'
          path: '.'
          format: 'HTML,SARIF'
          args: >
            --failOnCVSS 7
            --enableRetired
            --scan "**/*.jar"
            --scan "**/*.war"
            --scan "**/*.ear"
            --scan "**/*.zip"
        env:
          JAVA_OPTS: '-Xmx4g'

      - name: Upload Dependency-Check SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif

      - name: Upload Dependency-Check HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: reports/
          retention-days: 30

      # SAST для Java (SpotBugs)
      - name: Run SpotBugs SAST
        run: |
          chmod +x gradlew
          ./gradlew spotbugsMain spotbugsTest

      - name: Upload SpotBugs reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-reports
          path: build/reports/spotbugs/
          retention-days: 30